---
title: "Game Statistics on Escape!! Frisbee"
output: html_document
date: "2024-12-24"
editor_options: 
  chunk_output_type: console
---

Authorization
```{r}
library(googlesheets4)

# De-authorize any existing token
googlesheets4::gs4_deauth()

# Explicitly authorize with the appropriate scope
googlesheets4::gs4_auth(
  scopes = "https://www.googleapis.com/auth/spreadsheets.readonly"
)
```

Read the sheet
```{r}
url <- "https://docs.google.com/spreadsheets/d/1CPPBCwuwYP9lqWUS7Lu5ogXHtdpX_-i_lzcdtsohbwY/edit#gid=0"
Games.df <- googlesheets4::read_sheet(url,
                                        range = "A1:N",
                                        na = "NA",
                                        col_types = "cccncncccccnnn"
                                        )
```

```{r}
names(Games.df)
```
Average over all games
```{r}
mean(Games.df$Fundex)
sum(Games.df$DoubleTroubles) / sum(Games.df$TotalPoints)
```

Fundex by player
```{r}
plyr <- "Mike"

Games.df |>
#  dplyr::filter(Event == "Winter 24-25") |>
  dplyr::filter(Player1a == plyr | Player1b == plyr | Player2a == plyr | Player2b == plyr) |>
  dplyr::summarize(AvgFun = mean(Fundex),
                   MinFun = min(Fundex),
                   MaxFun = max(Fundex))
```

Statistics by player
```{r}
plyrs <- unique(c(Games.df$Player1a, Games.df$Player1b, Games.df$Player2a, Games.df$Player2b))

attach(Games.df)
Least <- NULL
Avg <- NULL
Most <- NULL
Games <- NULL
DT <- NULL
TP <- NULL
for(i in 1:length(plyrs)){
  Games = c(Games, length(Fundex[Player1a == plyrs[i] | Player1b == plyrs[i] | Player2a == plyrs[i] | Player2b == plyrs[i]]))
  Least = c(Least, min(Fundex[Player1a == plyrs[i] | Player1b == plyrs[i] | Player2a == plyrs[i] | Player2b == plyrs[i]]))
  Avg = c(Avg, mean(Fundex[Player1a == plyrs[i] | Player1b == plyrs[i] | Player2a == plyrs[i] | Player2b == plyrs[i]]))
  Most = c(Most, max(Fundex[Player1a == plyrs[i] | Player1b == plyrs[i] | Player2a == plyrs[i] | Player2b == plyrs[i]]))
  DT = c(DT, sum(DoubleTroubles[Player1a == plyrs[i] | Player1b == plyrs[i] | Player2a == plyrs[i] | Player2b == plyrs[i]]))
  TP = c(TP, sum(TotalPoints[Player1a == plyrs[i] | Player1b == plyrs[i] | Player2a == plyrs[i] | Player2b == plyrs[i]]))
  Avg2 = DT/TP
}
detach(Games.df)

Fundex.df <- data.frame(Player = plyrs, Games, 
                        Least = round(Least, 2), 
                        Average = round(Avg, 2), 
                        Most = round(Most, 2),
                        Average2 = round(Avg2, 2)) |>
  dplyr::filter(Games > 10) |>
  dplyr::arrange(desc(Average2))

```

Statistics by game type (Classic vs Escape!!)
```{r}
#remove <- c("Maya", "Augie", "Chris", "Cat") # least experienced players
Games.df |>
#  dplyr::filter(!Player1a %in% remove & !Player1b %in% remove & !Player2a %in% remove & !Player2b %in% remove) |>
  dplyr::group_by(PlayStyle) |>
  dplyr::summarise(Games = dplyr::n(),
                   Least = round(min(Fundex), 2),
                   AvgRatio = round(mean(Fundex), 2),
                   Most = round(max(Fundex), 2), 
                   DT = sum(DoubleTroubles),
                   TP = sum(TotalPoints),
                   Fun = DT/TP,
                   PercentGamesGT1 = sum(Fundex >= 1)/Games)
```

Statistics by court separation distance
```{r}
#remove <- c("Drew", "Craig", "Zack")
Games.df |>
#  dplyr::filter(!Player1a %in% remove & !Player1b %in% remove & !Player2a %in% remove & !Player2b %in% remove) |>
  dplyr::filter(Event == "Winter League") |>
  dplyr::group_by(CourtSeparation) |>
  dplyr::summarise(Games = dplyr::n(),
                   Least = round(min(Fundex), 2),
                   AvgRatio = round(mean(Fundex), 2),
                   Most = round(max(Fundex), 2), 
                   DT = sum(DoubleTroubles),
                   TP = sum(TotalPoints),
                   Fun = DT/TP,
                   FracGamesGT1 = sum(Fundex >= 1)/Games)
```

Which games were most "fun" by player
```{r}
plyr <- "Oscar"

Games.df |>
  dplyr::filter(Player1a == plyr | Player1b == plyr | Player2a == plyr | Player2b == plyr) |>
  dplyr::arrange(desc(Fundex)) |>
  dplyr::select(Date, Teams, Fundex)
```

